### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by rodrigoargumedo** [Hackalist/Hackalist.github.io#221]
As I develop the [2.0](https://github.com/Hackalist/Hackalist.github.io/tree/2.0) branch with better code readability and structure, here is what I have in my list:

- [x] Update the app to Angular 1.5.7
- [x] Add logo url field (#146)
- [ ] Ability to add events to its user calendar (#123)
- [x] MLH field (#151)
- [x] Add Bootstrap design support?
- [x] Implement Font Awesome (4.7 now, but 5.0 once it's released)
- [ ] Integrating some API for [flights](http://support.wan.travel/hc/en-us/articles/200191669) (See #122)
- [ ] Search engine via Algolia for searching hackathons

@paked's TODO:
- [ ] Testing to ensure that the JSON schema is fulfilled (#222 via https://github.com/Hackalist/Hackalist.github.io/issues/221#issuecomment-258657754)

**Comment by paked** [comment]
I strongly disagree with the idea of moving to anything that relies on us
hosting a server. Part of the beauty of Hackalist right now is that once
your PR is merged it goes live immediately. Adding in a server component
would make this much more difficult, and at best would add moving parts
which will break. This same idea runs for external contributors, we've
already established that a lot of ours are first timers - adding in extra
hoops which they have to set up (Node, Gulp, Webpack, etc.) is really
raising the barrier to entry.

I'm also curious to hear your justification of Angular 2 in the first
place. IMO if it ain't broke don't fix it.

*on mobile, ask me to rephrase I'd you don't understand anything I've
punched into this virtual keyboard*

**Comment by paked** [comment]
Everything else sounds pretty great! Looking forward to it. Let me know if
you want me to tackle anything.

**Comment by rodrigoargumedo** [comment]
@paked Although, I can still use Angular 2.0 with JS without the TypeScript requirement (requires Node.js) and bring the app to the same original code but it will require more work into it.

**Comment by paked** [comment]
Why do we need to use Angular 2 at all? Is there an inherent problem with
our existing code base?

**Comment by rodrigoargumedo** [comment]
I don't see it at all, but the only thing I was really afraid of the requirement of the Node.js. So, I took a step back to only using via CDN with 1.5.7 update.

**Comment by rodrigoargumedo** [comment]
I am going to throw this in here as well:

- [ ] Search Hackathons

**Comment by rodrigoargumedo** [comment]
@paked I forgot to mention about my intentions of moving the code to Angular 2: 

I was really curious to play around with some of the new stuff with Angular but then, adding the server component would be _next to_ impossible to maintain the code with that much of the work on our end. Plus, putting the new contributors with that is just quite a hassle to not just them, and as well for us, the team here. 

So, I scaled back to the original perspective of the code and upgraded the Angular version to 1.5.7 for the new features to toy with. I honestly think it is a **mistake** to me to move it over.

**Comment by paked** [comment]
@rodrigoargumedo: So to confirm, we are upgrading to Angular `1.5.7` and not using Angular 2 or any new technology which would add the necessity of a server-side backend? Wonderful.

**Comment by paked** [comment]
@rodrigoargumedo: What is the advantage of using Algolia over the built in search/filter functionality of Angular?

**Comment by paked** [comment]
I'll add this to the list of things to do:

- [ ] Testing to ensure that the JSON schema is fulfilled (Prevent issues like #222)

**Comment by rodrigoargumedo** [comment]
I am not going to upgrade to Angular 2. Scrap what I originally said before and we are to upgrade to `1.5.7` from `1.2.x.`

The advantage of Algolia is that it can create indexes and queries in just about seconds. That's the beauty of the Algolia search engine. It helps the users to find the hackathons if it is listed on the page. Might sound convenient there.

**Comment by rodrigoargumedo** [comment]
@paked Use this as a [reference](http://stackoverflow.com/questions/9838812/how-can-i-open-a-json-file-in-javascript-without-jquery)

**Comment by paked** [comment]
@rodrigoargumedo I finished that a few days ago: https://github.com/Hackalist/Hackalist.github.io/blob/master/test.js#L28-L41, it was merged in as part of #217.
